[package]
name = "so_utils"
version = "0.1.0"
authors = ["prodrive11 <p.bukowinski@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
kdb = { path = "../../", features = ["embedded"] }

[lib]
name = "so_utils"
crate-type = ["cdylib"]

